// <auto-generated />
namespace TheGioiLoa.Migrations.TheGioiLoaModel
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_guarantee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_guarantee));
        
        string IMigrationMetadata.Id
        {
            get { return "202003111223172_add_guarantee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
