// <auto-generated />
namespace TheGioiLoa.Migrations.TheGioiLoaModel
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class producthomepage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(producthomepage));
        
        string IMigrationMetadata.Id
        {
            get { return "202003211714366_producthomepage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
